### ISSUE TITLE
Get better results with decay in Delayed and non-stationary multi-armed bandit problems example

### ISSUE THREAD

**Issue by cdagnino** [bayesianbandits/bayesianbandits#112]
[This is a great](https://bayesianbandits.readthedocs.io/en/latest/notebooks/delayed-reward.html) example notebook, but the decay example doing worse is anticlimactic. Increasing the number of steps and playing around with the decay parameter can give better results. I can submit a PR if it's something that would be useful

**Comment by rishi-kulkarni** [comment]
Yeah, maybe with some kind of parameter search for the decay value? It's good to be clear that picking a good value can help, but picking a bad value can harm learning. 

Happy to review and merge that in if you can find the time!

**Comment by cdagnino** [comment]
@rishi-kulkarni I've sent a PR #115 but I'm not getting the expected results, so I'm happy to receive any feedback :D

You can assign this issue to me if that works for you.
