### ISSUE TITLE
Bug in Sparse LU decomposition 

### ISSUE THREAD

**Issue by vemarotta** [bayesianbandits/bayesianbandits#54]
When computing the LU decomposition of a sparse, square matrix, permutation of the columns will not guarantee that the LU decomposition is equal to the Cholesky decomposition. 

Potential fix: set permc_spec="NATURAL" in splu, to keep the natural order of the columns

**Comment by rishi-kulkarni** [comment]
This is fixed in https://github.com/bayesianbandits/bayesianbandits/releases/tag/v0.5.2. I added a number of ill-conditioned matrices that "fool" the default COLAMD permuter that are successfully decomposed when the permutation strategy is NATURAL.
